version: '3'
services:
  redis:
    image: redis:7.2.0-alpine
    container_name: redis
    ports:
      - 6379:6379
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ck
      MYSQL_DATABASE: ck
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d